// based on
// https://gist.github.com/radiantly/e1c7319214c77fa007f323fc56cd0239

// list of events to be blocked
const events = [
    "blur",
    "click",
    "contextmenu",
    "dblclick",
    "focus",
    "focusin",
    "focusout",
    "mousedown",
    "mouseout",
    "mouseover",
    "mouseup",
    "touchcancel",
    "touchchend",
    "touchstart",
]

function dontPropagate(event) {
    // only block if event was generated by a link
    if (isLink(event.target)) {
        event.stopImmediatePropagation()
    }
}

function isLink(node) {
    const closestLink = node.closest("a")
    return closestLink && closestLink.href
}

for (let eventName of events) {
    window.addEventListener(eventName, dontPropagate, true)
}
